<?php
/**
 * Fix the final 105 records with English text
 */

$host = 'localhost';
$dbname = 'langol_krishi_sahayak';
$username = 'root';
$password = '';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "Fixing final 105 records...\n\n";
    
    $fixes = [
        'Wari TSO' => 'ওয়ারী টিএসও',
        'Mohammadpur Housing' => 'মোহাম্মদপুর হাউজিং',
        'Posta TSO' => 'পোস্তা টিএসও',
        'Sangsad Bhaban TSO' => 'সংসদ ভবন টিএসও',
        'Jahangirnagar University' => 'জাহাঙ্গীরনগর বিশ্ববিদ্যালয়',
        'Saver P.A.T.C' => 'সাভার পিএটিসি',
        'Amin Bazar' => 'আমিন বাজার',
        'Pura EDSO' => 'পুরা ইডিএসও',
        'Medini Mandal EDSO' => 'মেদিনী মন্ডল ইডিএসও',
        'Bhaggyakul' => 'ভাগ্যকুল',
        'UMC Jute Mills' => 'ইউএমসি জুট মিলস',
        'Char Sindhur' => 'চর সিন্দুর',
        'B.O.F' => 'বিওএফ',
        'Manikganj Bazar' => 'মানিকগঞ্জ বাজার',
        'joymantop' => 'জয়মন্টপ',
        'Gorai' => 'গোড়াই',
        'Nagarbari SO' => 'নগরবাড়ী এসও',
        'D. Pakutia' => 'ডি. পাকুটিয়া',
        'Jamuna Sar Karkhana' => 'যমুনা সার কারখানা',
        'Sylhet Biman Bondar' => 'সিলেট বিমান বন্দর',
        'Shahajalal Science &' => 'শাহজালাল বিজ্ঞান ও প্রযুক্তি',
        'Natun Bazar' => 'নতুন বাজার',
        'Dhaka Dakkhin' => 'ঢাকা দক্ষিণ',
        'Dakkhin Bhadashore' => 'দক্ষিণ ভাদাশোর',
        'Ichhamati' => 'ইছামতি',
        'Moulvibazar Sadar' => 'মৌলভীবাজার সদর',
        'Barakapan' => 'বারকাপন',
        'Monumukh' => 'মনুমুখ',
        'Afrozganj' => 'আফরোজগঞ্জ',
        'Islamia Madrasha' => 'ইসলামিয়া মাদ্রাসা',
        'Noakhali College' => 'নোয়াখালী কলেজ',
        'Bhabani Jibanpur' => 'ভবানী জীবনপুর',
        'Thanar Hat' => 'থানার হাট',
        'Amisha Para' => 'আমিশা পাড়া',
        'B.I.T Post Office' => 'বিআইটি পোস্ট অফিস',
        'Khagrachari Sadar' => 'খাগড়াছড়ি সদর',
        'Kaptai Nuton Bazar' => 'কাপ্তাই নতুন বাজার',
        'Dinajpur Rajbari' => 'দিনাজপুর রাজবাড়ী',
        'Bogra Sadar' => 'বগুড়া সদর',
        'Bogra Canttonment' => 'বগুড়া ক্যান্টনমেন্ট',
        'Joypurhat Sadar' => 'জয়পুরহাট সদর',
        'Natore Sadar' => 'নাটোর সদর',
        'Digapatia' => 'দিঘাপতিয়া',
        'Baiddyabal Gharia' => 'বৈদ্যবল ঘরিয়া',
        'Madhnagar' => 'মাধনগর',
        'Sirajganj Sadar' => 'সিরাজগঞ্জ সদর',
        'Raipur' => 'রায়পুর',
        'Rashidabad' => 'রশিদাবাদ',
        'Porjana' => 'পোরজনা',
        'Kushtia Mohini' => 'কুষ্টিয়া মোহিনী',
        'Jessore Sadar' => 'যশোর সদর',
        'Jessore Upa-Shahar' => 'যশোর উপশহর',
        'Chanchra' => 'চাঁচড়া',
        'Jessore canttonment' => 'যশোর ক্যান্টনমেন্ট',
        'Jessore Airbach' => 'যশোর এয়ারবেস',
        'Rupdia' => 'রূপদিয়া',
        'Basundia' => 'বসুন্দিয়া',
        'Churamankathi' => 'চুরমনকাঠি',
        'Narail Sadar' => 'নড়াইল সদর',
        'Ratanganj' => 'রতনগঞ্জ',
        'Rajbari Sadar' => 'রাজবাড়ী সদর',
        'Goalanda' => 'গোয়ালন্দ',
        'Khankhanapur' => 'খানখানাপুর',
        'Shariatpur Sadar' => 'শরীয়তপুর সদর',
        'Angaria' => 'আঙ্গারিয়া',
        'Chikandi' => 'চিকন্দি',
        'Ratoil' => 'রাতাইল',
        'Barishal Cadet' => 'বরিশাল ক্যাডেট',
        'Padri Shibpur' => 'পাদ্রী শিবপুর',
        'Khulna G.P.O' => 'খুলনা জিপিও',
        'Chalna Ankorage' => 'চালনা অ্যাঙ্করেজ',
        'Mongla Port' => 'মংলা বন্দর',
        'Bhanganpar Bazar' => 'ভাঙ্গানপাড় বাজার',
        'Satkhira Sadar' => 'সাতক্ষীরা সদর',
        'Satkhira Islamia Acc' => 'সাতক্ষীরা ইসলামিয়া একাডেমি',
        'Gunakar kati' => 'গুনাকর কাটি',
        'Budhhat' => 'বুধহাট',
        'Jashore Sadar' => 'যশোর সদর',
        'Bogura Sadar' => 'বগুড়া সদর',
        'Chapai Nawabganj' => 'চাঁপাইনবাবগঞ্জ',
        'Chapai Nawabganj Sadar' => 'চাঁপাইনবাবগঞ্জ সদর',
        'Chapinawabganj Sadar' => 'চাঁপাইনবাবগঞ্জ সদর',
        'Chapinawbganj Sadar' => 'চাঁপাইনবাবগঞ্জ সদর',
        'Panchagar Sadar' => 'পঞ্চগড় সদর',
        'Panchagra Sadar' => 'পঞ্চগড় সদর',
        'Thakurgaon Sadar' => 'ঠাকুরগাঁও সদর',
        'Nilphamari Sadar' => 'নীলফামারী সদর',
        'Lalmonirhat Sadar' => 'লালমনিরহাট সদর',
        'Kurigram Sadar' => 'কুড়িগ্রাম সদর',
        'Gaibandha Sadar' => 'গাইবান্ধা সদর',
        'Rangpur Sadar' => 'রংপুর সদর',
        'Sherpur Shadar' => 'শেরপুর সদর',
        'Mymensingh Sadar' => 'ময়মনসিংহ সদর',
        'Netrakona Sadar' => 'নেত্রকোনা সদর',
        'Kishoreganj Sadar' => 'কিশোরগঞ্জ সদর',
        'Tangail Sadar' => 'টাঙ্গাইল সদর',
        'Manikganj Sadar' => 'মানিকগঞ্জ সদর',
        'Munshiganj Sadar' => 'মুন্সীগঞ্জ সদর',
        'Narayanganj Sadar' => 'নারায়ণগঞ্জ সদর',
        'Gazipur Sadar' => 'গাজীপুর সদর',
        'Narsingdi Sadar' => 'নরসিংদী সদর',
        'Faridpur Sadar' => 'ফরিদপুর সদর',
        'Faridpursadar' => 'ফরিদপুর সদর',
        'Madaripur Sadar' => 'মাদারীপুর সদর',
        'Gopalganj Sadar' => 'গোপালগঞ্জ সদর',
        'Sylhet Sadar' => 'সিলেট সদর',
        'Sylhe Sadar' => 'সিলেট সদর',
        'Sunamganj Sadar' => 'সুনামগঞ্জ সদর',
        'Habinagar' => 'হবিনগর',
        'Hobiganj Sadar' => 'হবিগঞ্জ সদর',
        'Bagerhat Sadar' => 'বাগেরহাট সদর',
        'Khulna Sadar' => 'খুলনা সদর',
        'Khula Sadar' => 'খুলনা সদর',
        'Magura Sadar' => 'মাগুরা সদর',
        'Jinaidaha Sadar' => 'ঝিনাইদহ সদর',
        'Chuadanga Sadar' => 'চুয়াডাঙ্গা সদর',
        'Meherpur Sadar' => 'মেহেরপুর সদর',
        'Pabna Sadar' => 'পাবনা সদর',
        'Rajshahi Sadar' => 'রাজশাহী সদর',
        'Naogaon Sadar' => 'নওগাঁ সদর',
        'Bhola Sadar' => 'ভোলা সদর',
        'Barishal Sadar' => 'বরিশাল সদর',
        'Jhalokathi Sadar' => 'ঝালকাঠি সদর',
        'Pirojpur Sadar' => 'পিরোজপুর সদর',
        'Barguna Sadar' => 'বরগুনা সদর',
        'Patuakhali Sadar' => 'পটুয়াখালী সদর',
        'Coxs Bazar Sadar' => 'কক্সবাজার সদর',
        'Rangamati Sadar' => 'রাঙ্গামাটি সদর',
        'Bandarban Sadar' => 'বান্দরবান সদর',
        'Feni Sadar' => 'ফেনী সদর',
        'Noakhali Sadar' => 'নোয়াখালী সদর',
        'Lakshimpur Sadar' => 'লক্ষ্মীপুর সদর',
        'Laksmipur' => 'লক্ষ্মীপুর',
        'Chandpur Sadar' => 'চাঁদপুর সদর',
        'Brahamanbaria Sadar' => 'ব্রাহ্মণবাড়িয়া সদর',
        'Comilla Sadar' => 'কুমিল্লা সদর',
        'Chittagong Sadar' => 'চট্টগ্রাম সদর',
        'Chittagong Airport' => 'চট্টগ্রাম বিমানবন্দর',
        'Chittagong Bandar' => 'চট্টগ্রাম বন্দর',
        'Chittagong GPO' => 'চট্টগ্রাম জিপিও',
        'Chitt. Politechnic In' => 'চট্টগ্রাম পলিটেকনিক ইন্সটিটিউট',
        'Chitt. Customs Acca' => 'চট্টগ্রাম কাস্টমস একাডেমি',
        'Chitt. Sailers Colon' => 'চট্টগ্রাম নাবিক কলোনি',
        'Chitt. Cantonment' => 'চট্টগ্রাম ক্যান্টনমেন্ট',
        'BIT Khulna' => 'বিআইটি খুলনা',
        'BIDS' => 'বিআইডিএস',
        'B.R.R' => 'বিআরআর',
        'D.C Mills' => 'ডিসি মিলস',
        'LN Mills' => 'এলএন মিলস',
        'P.C College' => 'পিসি কলেজ',
        'M.C. College' => 'এমসি কলেজ',
        'Nizamuddin College' => 'নিজামউদ্দিন কলেজ',
        'Ramdia College' => 'রামদিয়া কলেজ',
        'Rangpur Carmiecal Col' => 'রংপুর কারমাইকেল কলেজ',
        'Rangpur Cadet Colleg' => 'রংপুর ক্যাডেট কলেজ',
        'Sylhet Cadet Col' => 'সিলেট ক্যাডেট কলেজ',
        'Jinaidaha Cadet College' => 'ঝিনাইদহ ক্যাডেট কলেজ',
        'Rajshahi University' => 'রাজশাহী বিশ্ববিদ্যালয়',
        'Khulna University' => 'খুলনা বিশ্ববিদ্যালয়',
        'National University' => 'জাতীয় বিশ্ববিদ্যালয়',
        'Islami University' => 'ইসলামী বিশ্ববিদ্যালয়',
        'Agriculture Universi' => 'কৃষি বিশ্ববিদ্যালয়',
        'Darul Ulam' => 'দারুল উলুম',
        'Palli Unnyan Accadem' => 'পল্লী উন্নয়ন একাডেমি',
        'Export Processing' => 'এক্সপোর্ট প্রসেসিং জোন',
        'Tejgaon Industrial Area' => 'তেজগাঁও শিল্প এলাকা',
        'Atra Shilpa Area' => 'আত্রা শিল্প এলাকা',
        'Khulna Shipyard' => 'খুলনা শিপইয়ার্ড',
        'Chhatak Cement Facto' => 'ছাতক সিমেন্ট ফ্যাক্টরি',
        'Chhatak Paper Mills' => 'ছাতক পেপার মিলস',
        'Ghorashal Urea Facto' => 'ঘোড়াশাল ইউরিয়া ফ্যাক্টরি',
        'Kashem Cotton Mills' => 'কাশেম কটন মিলস',
        'Kaliko Cotton Mills' => 'কালিকো কটন মিলস',
        'Amin Jute Mills' => 'আমিন জুট মিলস',
        'Dhaka Jute Mills' => 'ঢাকা জুট মিলস',
        'Sonali Jute Mills' => 'সোনালী জুট মিলস',
        'Kishoreganj S.Mills' => 'কিশোরগঞ্জ সুগার মিলস',
        'Dewangonj S. Mills' => 'দেওয়ানগঞ্জ সুগার মিলস',
        'Rajshahi Sugar Mills' => 'রাজশাহী সুগার মিলস',
        'Nilphamari Sugar Mil' => 'নীলফামারী সুগার মিলস',
        'Dhaka GPO' => 'ঢাকা জিপিও',
        'Dhaka Sadar HO' => 'ঢাকা সদর এইচও',
        'Wari TSO' => 'ওয়ারী টিএসও',
        'Gendaria TSO' => 'গেন্ডারিয়া টিএসও',
        'Jigatala TSO' => 'জিগাতলা টিএসও',
        'Mohammadpur Housing' => 'মোহাম্মদপুর হাউজিং',
        'Sangsad Bhaban TSO' => 'সংসদ ভবন টিএসও',
        'Tejgaon TSO' => 'তেজগাঁও টিএসও',
        'Gulshan Model Town' => 'গুলশান মডেল টাউন',
        'Banani TSO' => 'বনানী টিএসও',
        'New Market TSO' => 'নিউ মার্কেট টিএসও',
        'Dhaka Cantonment TSO' => 'ঢাকা ক্যান্টনমেন্ট টিএসও',
        'Mirpur TSO' => 'মিরপুর টিএসও',
        'Shantinagr TSO' => 'শান্তিনগর টিএসও',
        'Basabo TSO' => 'বাসাবো টিএসও',
        'Khilgaon TSO' => 'খিলগাঁও টিএসও',
        'Khilkhet TSO' => 'খিলক্ষেত টিএসও',
        'Uttara Model Twon TSO' => 'উত্তরা মডেল টাউন টিএসও',
        'Dilkusha TSO' => 'দিলকুশা টিএসও',
        'Bangabhaban TSO' => 'বঙ্গভবন টিএসও',
        'Posta TSO' => 'পোস্তা টিএসও',
        'Rampura TSO' => 'রামপুরা টিএসও',
        'Dhania TSO' => 'ধনিয়া টিএসও',
        'Savar Canttonment' => 'সাভার ক্যান্টনমেন্ট',
        'Rajendrapur Canttome' => 'রাজেন্দ্রপুর ক্যান্টনমেন্ট',
        'Jalalabad Cantoment' => 'জালালাবাদ ক্যান্টনমেন্ট',
        'Jahanabad Canttonmen' => 'জাহানাবাদ ক্যান্টনমেন্ট',
        'Rajshahi Canttonment' => 'রাজশাহী ক্যান্টনমেন্ট',
        'Bogra Canttonment' => 'বগুড়া ক্যান্টনমেন্ট',
        'Jessore canttonment' => 'যশোর ক্যান্টনমেন্ট',
        'Comilla Contoment' => 'কুমিল্লা ক্যান্টনমেন্ট',
        'Al- Amin Baria Madra' => 'আল-আমিন বাড়িয়া মাদ্রাসা',
        'Baitulaman Politecni' => 'বায়তুল আমান পলিটেকনিক',
        'Dhaka Politechnic' => 'ঢাকা পলিটেকনিক',
        'Mujib Nagar Complex' => 'মুজিব নগর কমপ্লেক্স',
        'Kaptai Project' => 'কাপ্তাই প্রজেক্ট',
        'Bishwa jaker Manjil' => 'বিশ্ব জাকের মঞ্জিল',
        'Osman Manjil' => 'ওসমান মঞ্জিল',
        'Iqbal Park' => 'ইকবাল পার্ক',
        'Patia Head Office' => 'পটিয়া প্রধান কার্যালয়',
        'Ramghar Head Office' => 'রামগড় প্রধান কার্যালয়',
        'Chiringga S.O' => 'চিরিঙ্গা এসও',
        'Haldia SO' => 'হালদিয়া এসও',
        'Kulaghat SO' => 'কুলাঘাট এসও',
        'Lalpur S.O' => 'লালপুর এসও',
        'Vaggyakul SO' => 'ভাগ্যকুল এসও',
        'Haridia DESO' => 'হরিদিয়া ডিএসও',
        'Medini Mandal EDSO' => 'মেদিনী মন্ডল ইডিএসও',
        'Pura EDSO' => 'পুরা ইডিএসও',
        'Saver P.A.T.C' => 'সাভার পিএটিসি',
        'B.O.F' => 'বিওএফ',
        'B.I.T Post Office' => 'বিআইটি পোস্ট অফিস',
        'UMC Jute Mills' => 'ইউএমসি জুট মিলস',
        'Thakurgaon Road' => 'ঠাকুরগাঁও রোড',
        'Ullapara R.S' => 'উল্লাপাড়া আরএস',
        'Chalna Ankorage' => 'চালনা অ্যাঙ্করেজ',
        'Mongla Port' => 'মংলা বন্দর',
        'Benapole' => 'বেনাপোল',
        'Hili' => 'হিলি',
        'Bangla Hili' => 'বাংলা হিলি',
        'Darshana' => 'দর্শনা',
        'Teknaf' => 'টেকনাফ',
        'St.Martin' => 'সেন্ট মার্টিন',
        'Coxs Bazar' => 'কক্সবাজার',
        'Kuakata' => 'কুয়াকাটা',
        'Srimangal' => 'শ্রীমঙ্গল',
        'Jaflong' => 'জাফলং',
        'Tamabil' => 'তামাবিল',
        'Bhomra' => 'ভোমরা',
        'Burimari' => 'বুড়িমারী',
        'Akhaura' => 'আখাউড়া',
        'Bibir Bazar' => 'বিবির বাজার',
        'Sonamasjid' => 'সোনামসজিদ',
        'Haluaghat' => 'হালুয়াঘাট',
        'Gobrakura' => 'গোবরাকুড়া',
        'Koroitoli' => 'কড়ইতলী',
        'Bholaganj' => 'ভোলাগঞ্জ',
        'Sheola' => 'শেওলা',
        'Zakiganj' => 'জকিগঞ্জ',
        'Chatlapur' => 'চাতলাপুর',
        'Balla' => 'বাল্লা',
        'Dhanua Kamalpur' => 'ধনুয়া কামালপুর',
        'Nakugaon' => 'নাকুগাঁও',
        'Banglabandha' => 'বাংলাবান্ধা',
        'Biral' => 'বিরল',
        'Radhikapur' => 'রাধিকাপুর',
        'Rohanpur' => 'রহনপুর',
        'Singhabad' => 'সিংহবাদ',
        'Birol' => 'বিরল',
        'Darshana' => 'দর্শনা',
        'Gede' => 'গেদে',
        'Benapole' => 'বেনাপোল',
        'Petrapole' => 'পেট্রাপোল',
        'Hili' => 'হিলি',
        'Burimari' => 'বুড়িমারী',
        'Changrabandha' => 'চ্যাংড়াবান্ধা',
        'Sonamasjid' => 'সোনামসজিদ',
        'Mahadipur' => 'মহদিপুর',
        'Akhaura' => 'আখাউড়া',
        'Agartala' => 'আগরতলা',
        'Tamabil' => 'তামাবিল',
        'Dawki' => 'ডাউকি',
        'Bibir Bazar' => 'বিবির বাজার',
        'Srimantapur' => 'শ্রীমন্তপুর',
        'Bhomra' => 'ভোমরা',
        'Ghojadanga' => 'ঘোজাডাঙ্গা',
        'Haluaghat' => 'হালুয়াঘাট',
        'Gachuapara' => 'গাছুয়াপাড়া',
        'Gobrakura' => 'গোবরাকুড়া',
        'Koroitoli' => 'কড়ইতলী',
        'Bholaganj' => 'ভোলাগঞ্জ',
        'Sheola' => 'শেওলা',
        'Sutarkandi' => 'সুতারকান্দি',
        'Zakiganj' => 'জকিগঞ্জ',
        'Karimganj' => 'করিমগঞ্জ',
        'Chatlapur' => 'চাতলাপুর',
        'Manu' => 'মনু',
        'Balla' => 'বাল্লা',
        'Khowai' => 'খোয়াই',
        'Dhanua Kamalpur' => 'ধনুয়া কামালপুর',
        'Mahendraganj' => 'মহেন্দ্রগঞ্জ',
        'Nakugaon' => 'নাকুগাঁও',
        'Dalu' => 'ডালু',
        'Banglabandha' => 'বাংলাবান্ধা',
        'Phulbari' => 'ফুলবাড়ী',
        'Biral' => 'বিরল',
        'Radhikapur' => 'রাধিকাপুর',
        'Rohanpur' => 'রহনপুর',
        'Singhabad' => 'সিংহবাদ',
        'Birol' => 'বিরল',
        'Darshana' => 'দর্শনা',
        'Gede' => 'গেদে',
        'Benapole' => 'বেনাপোল',
        'Petrapole' => 'পেট্রাপোল',
        'Hili' => 'হিলি',
        'Burimari' => 'বুড়িমারী',
        'Changrabandha' => 'চ্যাংড়াবান্ধা',
        'Sonamasjid' => 'সোনামসজিদ',
        'Mahadipur' => 'মহদিপুর',
        'Akhaura' => 'আখাউড়া',
        'Agartala' => 'আগরতলা',
        'Tamabil' => 'তামাবিল',
        'Dawki' => 'ডাউকি',
        'Bibir Bazar' => 'বিবির বাজার',
        'Srimantapur' => 'শ্রীমন্তপুর',
        'Bhomra' => 'ভোমরা',
        'Ghojadanga' => 'ঘোজাডাঙ্গা',
        'Haluaghat' => 'হালুয়াঘাট',
        'Gachuapara' => 'গাছুয়াপাড়া',
        'Gobrakura' => 'গোবরাকুড়া',
        'Koroitoli' => 'কড়ইতলী',
        'Bholaganj' => 'ভোলাগঞ্জ',
        'Sheola' => 'শেওলা',
        'Sutarkandi' => 'সুতারকান্দি',
        'Zakiganj' => 'জকিগঞ্জ',
        'Karimganj' => 'করিমগঞ্জ',
        'Chatlapur' => 'চাতলাপুর',
        'Manu' => 'মনু',
        'Balla' => 'বাল্লা',
        'Khowai' => 'খোয়াই',
        'Dhanua Kamalpur' => 'ধনুয়া কামালপুর',
        'Mahendraganj' => 'মহেন্দ্রগঞ্জ',
        'Nakugaon' => 'নাকুগাঁও',
        'Dalu' => 'ডালু',
        'Banglabandha' => 'বাংলাবান্ধা',
        'Phulbari' => 'ফুলবাড়ী',
    ];
    
    $count = 0;
    foreach ($fixes as $en => $bn) {
        // Fix post_office_bn
        $stmt = $pdo->prepare("
            UPDATE location 
            SET post_office_bn = :bn 
            WHERE post_office = :en OR post_office_bn = :en
        ");
        $stmt->execute([':bn' => $bn, ':en' => $en]);
        $count += $stmt->rowCount();
        
        // Fix upazila_bn
        $stmt = $pdo->prepare("
            UPDATE location 
            SET upazila_bn = :bn 
            WHERE upazila = :en OR upazila_bn = :en
        ");
        $stmt->execute([':bn' => $bn, ':en' => $en]);
        $count += $stmt->rowCount();
        
        // Fix district_bn
        $stmt = $pdo->prepare("
            UPDATE location 
            SET district_bn = :bn 
            WHERE district = :en OR district_bn = :en
        ");
        $stmt->execute([':bn' => $bn, ':en' => $en]);
        $count += $stmt->rowCount();
    }
    
    echo "Fixed $count records with specific mappings.\n\n";
    
    // Final regex cleanup for any remaining English
    echo "Checking for remaining English...\n";
    $remaining = $pdo->query("
        SELECT COUNT(*) as cnt 
        FROM location 
        WHERE post_office_bn REGEXP '[A-Za-z]' 
           OR upazila_bn REGEXP '[A-Za-z]'
    ")->fetch(PDO::FETCH_ASSOC);
    
    if ($remaining['cnt'] > 0) {
        echo "Still {$remaining['cnt']} records with English. Applying pattern fixes...\n";
        
        $patterns = [
            'TSO' => 'টিএসও',
            'EDSO' => 'ইডিএসও',
            'GPO' => 'জিপিও',
            'SO' => 'এসও',
            'Sadar' => 'সদর',
            'Bazar' => 'বাজার',
            'Hat' => 'হাট',
            'College' => 'কলেজ',
            'School' => 'স্কুল',
            'Madrasa' => 'মাদ্রাসা',
            'Madrasha' => 'মাদ্রাসা',
            'University' => 'বিশ্ববিদ্যালয়',
            'Institute' => 'ইন্সটিটিউট',
            'Centre' => 'সেন্টার',
            'Center' => 'সেন্টার',
            'Complex' => 'কমপ্লেক্স',
            'Project' => 'প্রজেক্ট',
            'Mills' => 'মিলস',
            'Factory' => 'ফ্যাক্টরি',
            'Area' => 'এলাকা',
            'Town' => 'টাউন',
            'Model' => 'মডেল',
            'Housing' => 'হাউজিং',
            'Road' => 'রোড',
            'Port' => 'বন্দর',
            'Airport' => 'বিমানবন্দর',
            'Station' => 'স্টেশন',
            'Office' => 'অফিস',
            'Head' => 'হেড',
            'Branch' => 'শাখা',
            'Bank' => 'ব্যাংক',
            'Hospital' => 'হাসপাতাল',
            'Clinic' => 'ক্লিনিক',
            'Market' => 'মার্কেট',
            'Super' => 'সুপার',
            'Plaza' => 'প্লাজা',
            'Tower' => 'টাওয়ার',
            'Garden' => 'বাগান',
            'Park' => 'পার্ক',
            'Gate' => 'গেট',
            'Bridge' => 'ব্রিজ',
            'Ferry' => 'ফেরি',
            'Ghat' => 'ঘাট',
            'Terminal' => 'টার্মিনাল',
            'Stand' => 'স্ট্যান্ড',
            'Stop' => 'স্টপ',
            'More' => 'মোড়',
            'Point' => 'পয়েন্ট',
            'Corner' => 'কর্নার',
            'View' => 'ভিউ',
            'Villa' => 'ভিলা',
            'House' => 'হাউজ',
            'Home' => 'হোম',
            'Lodge' => 'লজ',
            'Cottage' => 'কটেজ',
            'Apartment' => 'অ্যাপার্টমেন্ট',
            'Flat' => 'ফ্ল্যাট',
            'Building' => 'বিল্ডিং',
            'Mansion' => 'ম্যানশন',
            'Palace' => 'প্যালেস',
            'Castle' => 'ক্যাসেল',
            'Fort' => 'ফোর্ট',
            'Camp' => 'ক্যাম্প',
            'Base' => 'বেস',
            'Line' => 'লাইন',
            'Lane' => 'লেন',
            'Street' => 'স্ট্রিট',
            'Avenue' => 'এভিনিউ',
            'Block' => 'ব্লক',
            'Sector' => 'সেক্টর',
            'Zone' => 'জোন',
            'Ward' => 'ওয়ার্ড',
            'Union' => 'ইউনিয়ন',
            'Thana' => 'থানা',
            'District' => 'জেলা',
            'Division' => 'বিভাগ',
            'Village' => 'গ্রাম',
            'Para' => 'পাড়া',
            'Mohalla' => 'মহল্লা',
            'Colony' => 'কলোনি',
            'Society' => 'সোসাইটি',
            'Nagar' => 'নগর',
            'Pur' => 'পুর',
            'Ganj' => 'গঞ্জ',
            'Gram' => 'গ্রাম',
            'Bari' => 'বাড়ী',
            'Ghar' => 'ঘর',
            'Khana' => 'খানা',
            'Dighi' => 'দীঘি',
            'Pukur' => 'পুকুর',
            'Beel' => 'বিল',
            'Haor' => 'হাওর',
            'Baor' => 'বাওড়',
            'Char' => 'চর',
            'Dwip' => 'দ্বীপ',
            'Island' => 'আইল্যান্ড',
            'River' => 'নদী',
            'Khal' => 'খাল',
            'Lake' => 'লেক',
            'Sea' => 'সাগর',
            'Ocean' => 'মহাসাগর',
            'Hill' => 'পাহাড়',
            'Mountain' => 'পর্বত',
            'Forest' => 'বন',
            'Jungle' => 'জঙ্গল',
            'Field' => 'মাঠ',
            'Ground' => 'মাঠ',
            'Stadium' => 'স্টেডিয়াম',
            'Club' => 'ক্লাব',
            'Association' => 'সমিতি',
            'Organization' => 'সংস্থা',
            'Foundation' => 'ফাউন্ডেশন',
            'Trust' => 'ট্রাস্ট',
            'Mission' => 'মিশন',
            'Church' => 'গির্জা',
            'Mosque' => 'মসজিদ',
            'Temple' => 'মন্দির',
            'Pagoda' => 'প্যাগোডা',
            'Ashram' => 'আশ্রম',
            'Mazar' => 'মাজার',
            'Dargah' => 'দরগাহ',
            'Eidgah' => 'ঈদগাহ',
            'Graveyard' => 'কবরস্থান',
            'Cemetery' => 'সমাধিস্থল',
            'Crematorium' => 'শ্মশান',
        ];
        
        foreach ($patterns as $en => $bn) {
            $stmt = $pdo->prepare("
                UPDATE location 
                SET post_office_bn = REPLACE(post_office_bn, :en, :bn),
                    upazila_bn = REPLACE(upazila_bn, :en, :bn)
                WHERE post_office_bn LIKE CONCAT('%', :en, '%') 
                   OR upazila_bn LIKE CONCAT('%', :en, '%')
            ");
            $stmt->execute([':en' => $en, ':bn' => $bn]);
        }
    }
    
    // Final check
    $final = $pdo->query("
        SELECT COUNT(*) as cnt 
        FROM location 
        WHERE post_office_bn REGEXP '[A-Za-z]' 
           OR upazila_bn REGEXP '[A-Za-z]'
    ")->fetch(PDO::FETCH_ASSOC);
    
    echo "Final remaining English records: {$final['cnt']}\n";
    
    if ($final['cnt'] == 0) {
        echo "✅ ALL DONE! Database is 100% Bangla.\n";
    } else {
        echo "Still some left. Please check manually.\n";
    }
    
} catch (PDOException $e) {
    die("Error: " . $e->getMessage());
}
